### ISSUE TITLE
TypeError: undefined is not a function (deferrableSelections)

### ISSUE THREAD

**Issue by rbadr** [relay-tools/react-relay-network-modern#38]
Hi, 

After upgrading from version 2.3.3 to 2.3.4, I'm starting to get this error intermittently when fetching a query: 

```
TypeError: undefined is not a function (evaluating '(deferrableSelections \|\| new Set())[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
--

```
Note : I'm using it in a react native project

Any ideas? Thanks.

**Comment by nodkz** [comment]
Here is comparison between versions https://github.com/relay-tools/react-relay-network-modern/compare/v2.3.3...v2.3.4

Notable change which may affect your error was upgrading from babe6 on babel7.

And your error message related to `for of` syntax https://github.com/babel/babel/issues/8089#issuecomment-393894835

But `for of` syntax does not used in `react-relay-network-modern`.

Can you provide stack trace for your error? And can you confirm that was updated only `react-relay-network-modern` in your package.json and other packages cannot throw this error?

Tnx

**Comment by rbadr** [comment]
Thanks for you quick response :) 

Sorry, I couldn't copy the stacktrace but here is a screenshot, it seems to be a problem with relay-runtime : 

![error](https://user-images.githubusercontent.com/18709320/45687596-8ac86700-bb4f-11e8-8882-3115882e2ef7.png)


I can confirm that this error only appears when I upgrade react-relay-network-modern. 
The version of relay-runtime is 1.6.2

Thanks

**Comment by nodkz** [comment]
Add the following polyfill for Android to your `index.js` file:

```js
import { Platform } from 'react-native';

if (Platform.OS === 'android') {
  // Fix error on Android
  // undefined is not a function(evaluating '_iterator[typeof Symbol === "function"?Symbol.iterator:"@@iterator"]()')
  // see https://github.com/facebook/react-native/issues/15902#issuecomment-375521246
  global.Symbol = require('core-js/es6/symbol');
  require('core-js/fn/symbol/iterator');
  require('core-js/fn/map');
  require('core-js/fn/set');
  require('core-js/fn/array/find');
}
```

It looks like that `react-relay-network-modern` has such polyfill inside, and after upgrading to babel@7 it was removed due to absence (for .. of, or other iterating method) code inside this package.

So, for now, you should add polyfill explicitly to your app for Android devices.

**Comment by rbadr** [comment]
Ok I will. Thanks for the help !
